routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');


Auth::routes();
Route::get('/logout', 'Auth\LoginController@logout');


Route::get('/home', 'HomeController@index');
Route::get('/article', 'HomeController@article');
Route::get('/post/{post_id}/{slug?}', 'PostsController@post');
Route::get('/category/{category_id}/{slug?}', 'CategoryController@category');
Route::get('/subcategory/{subcategory_id}/{slug?}', 'CategoryController@subcategory');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    public function getSlugAttribute()
    {
        return str_slug($this->name);
    }

    public function getUrlAttribute()
    {
        return action('CategoryController@category', [$this->id, $this->slug]);
    }
}

app/Item.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Item extends Model
{
    //
}

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    //

    public function getSlugAttribute()
    {
        return str_slug($this->title);
    }

    public function getUrlAttribute()
    {
        return action('PostsController@post', [$this->id, $this->slug]);
    }
}

app/Price.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Price extends Model
{
    //
}

app/SubCategory.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class SubCategory extends Model
{
    public function getSlugAttribute()
    {
        return str_slug($this->name);
    }

    public function getUrlAttribute()
    {
        return action('CategoryController@subcategory', [$this->id, $this->slug]);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Post;
use App\SubCategory;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    public function category($id, $slug = '')
    {

        $category = Category::find($id);
        $sub_categories = SubCategory::where('category_id', $id)->paginate(20);

        if (is_null($category)){
            return redirect('/');
        } else{
            return view('category')->with(compact('category', 'sub_categories'));
        }

    }

    public function subcategory($id, $slug = '')
    {

        $subcategory = SubCategory::find($id);
        $posts = Post::where('sub_category_id', $id)->paginate(15);

        if (is_null($subcategory)){
            return redirect('/');
        } else{
            return view('subcategory')->with(compact('subcategory', 'posts'));
        }

    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Post;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
//    public function __construct()
//    {
//        $this->middleware('auth');
//    }


    public function index()
    {
        $categories = Category::orderBy('id', 'desc')->paginate(20);
        $recentPosts = Post::orderBy('id', 'desc')->limit(4)->get();
        $latest = Post::orderBy('id', 'desc')->limit(1)->first();

        return view('home')->with(compact('categories','recentPosts', 'latest'));
    }

    public function article()
    {
        return view('post');
    }
}

app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;

use App\Item;
use App\Post;
use Illuminate\Http\Request;

class PostsController extends Controller
{
    public function post($id, $slug = '')
    {

        $post = Post::find($id);
        $items = Item::where('post_id', $id)->paginate(10);

        if (is_null($post)){
            return redirect('/');
        } else{
            return view('post')->with(compact('post','items'));
        }

    }
}

resources/views/category.blade.php
@extends('layouts.app')

@section('content')
    <div class="main">
        <div class="container">


            <!-- BEGIN SIDEBAR & CONTENT -->
            <div class="row margin-bottom-40">
                <!-- BEGIN CONTENT -->
                <div class="col-md-12 col-sm-12 margin-top-10">
                    <h1>{{$category->name}}</h1>
                    <div class="content-page">
                        <div class="row">
                            <!-- BEGIN LEFT SIDEBAR -->
                            <div class="col-md-9 col-sm-9 blog-item">

                               {!! $category->description !!}

                                 {{--<ul class="blog-info">--}}
                                    {{--<li><i class="fa fa-user"></i> By {{\App\User::where('email', $post->author)->first() ? \App\User::where('email', $post->author)->first()->name : "N/A"}}</li>--}}
                                    {{--<li><i class="fa fa-calendar"></i> {{$post->created_at->toDayDateTimeString()}}</li>--}}
                                    {{--<li><i class="fa fa-tags"></i> {{\App\SubCategory::find($post->sub_category_id)->name}}</li>--}}
                                {{--</ul>--}}

                                <hr>


                                @foreach($sub_categories as $sub_category)
                                    <!-- BEGIN SERVICES -->
                                    <div class="row front-team">
                                        <h3 class="no-top-space text-left"><a href="{{$sub_category->url}}">{{$sub_category->name}} </a></h3>
                                        <ul class="list-unstyled">

                                            @foreach(\App\Post::where('sub_category_id', $sub_category->id)->limit(3)->get() as $topPosts)
                                                <li class="col-md-4 col-sm-4 col-lg-4 col-xs-12">
                                                    <img alt="{{$topPosts->title}}" src="{{config('Droids.admin').$topPosts->image}}" width="270" height="230"  >
                                                    <h4>
                                                        <a href="{{$topPosts->url}}"> <strong>{{$topPosts->title}}</strong> </a>
                                                    </h4>

                                                    <p>
                                                        {{ str_limit(strip_tags($topPosts->description), $limit = 100, $end = '...') }}
                                                    </p>
                                                    <ul class="blog-info">
                                                        <li><i class="fa fa-user"></i> By {{\App\User::where('email', $topPosts->author)->first()->name}}</li>
                                                        <br>
                                                        <li><i class="fa fa-calendar"></i> {{$topPosts->created_at->toDayDateTimeString()}}</li>
                                                        {{--<li><i class="fa fa-comments"></i> 17</li>--}}
                                                        {{--<li><i class="fa fa-tags"></i> Tag1, tag2, tag3</li>--}}
                                                    </ul>
                                                </li>
                                            @endforeach

                                        </ul>
                                    </div>
                                    <!-- END SERVICES -->
                                    <hr style="height:1px;border:none;color:#333;background-color:#333;">
                                @endforeach




                            </div>
                            <!-- END LEFT SIDEBAR -->

                            <!-- BEGIN RIGHT SIDEBAR -->
                            <div class="col-md-3 col-sm-3 blog-sidebar">
                                <!-- CATEGORIES START -->
                                <h2 class="no-top-space">Top Categories</h2>
                                <ul class="nav sidebar-categories margin-bottom-40">
                                    @foreach(\App\Category::take(5)->get() as $category)
                                        <li><a href="{{$category->url}}">{{$category->name}}</a></li>
                                    @endforeach
                                </ul>
                                <!-- CATEGORIES END -->

                                <!-- BEGIN RECENT NEWS -->
                                <h2>Recent News</h2>
                                <div class="recent-news margin-bottom-10">
                                    <div class="row margin-bottom-10">
                                        <div class="col-md-3">
                                            <img class="img-responsive" alt="" src="assets/pages/img/people/img2-large.jpg">
                                        </div>
                                        <div class="col-md-9 recent-news-inner">
                                            <h3><a href="javascript:;">Letiusto gnissimos</a></h3>
                                            <p>Decusamus tiusto odiodig nis simos ducimus qui sint</p>
                                        </div>
                                    </div>
                                    <div class="row margin-bottom-10">
                                        <div class="col-md-3">
                                            <img class="img-responsive" alt="" src="assets/pages/img/people/img1-large.jpg">
                                        </div>
                                        <div class="col-md-9 recent-news-inner">
                                            <h3><a href="javascript:;">Deiusto anissimos</a></h3>
                                            <p>Decusamus tiusto odiodig nis simos ducimus qui sint</p>
                                        </div>
                                    </div>
                                    <div class="row margin-bottom-10">
                                        <div class="col-md-3">
                                            <img class="img-responsive" alt="" src="assets/pages/img/people/img3-large.jpg">
                                        </div>
                                        <div class="col-md-9 recent-news-inner">
                                            <h3><a href="javascript:;">Tesiusto baissimos</a></h3>
                                            <p>Decusamus tiusto odiodig nis simos ducimus qui sint</p>
                                        </div>
                                    </div>
                                </div>
                                <!-- END RECENT NEWS -->

                                <!-- BEGIN BLOG TALKS -->
                                <div class="blog-talks margin-bottom-30">
                                    <h2>Popular Talks</h2>
                                    <div class="tab-style-1">
                                        <ul class="nav nav-tabs">
                                            <li class="active"><a data-toggle="tab" href="#tab-1">Multipurpose</a></li>
                                            <li><a data-toggle="tab" href="#tab-2">Documented</a></li>
                                        </ul>
                                        <div class="tab-content">
                                            <div id="tab-1" class="tab-pane row-fluid fade in active">
                                                <p class="margin-bottom-10">Raw denim you probably haven't heard of them jean shorts Austin. eu banh mi, qui irure terry richardson ex squid Aliquip placeat salvia cillum iphone.</p>
                                                <p><a class="more" href="javascript:;">Read more</a></p>
                                            </div>
                                            <div id="tab-2" class="tab-pane fade">
                                                <p>Food truck fixie locavore, accusamus mcsweeney's marfa nulla single-origin coffee squid. aliquip jean shorts ullamco ad vinyl aesthetic magna delectus mollit. Keytar helvetica VHS salvia..</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- END BLOG TALKS -->


                                <!-- BEGIN BLOG TAGS -->
                                <div class="blog-tags margin-bottom-20">
                                    <h2>Tags</h2>
                                    <ul>
                                        @foreach(\App\SubCategory::all() as $subCat)
                                            <li><a href="{{$subCat->url}}"><i class="fa fa-tags"></i>{{$subCat->name}}</a></li>
                                        @endforeach
                                    </ul>
                                </div>
                                <!-- END BLOG TAGS -->
                            </div>
                            <!-- END RIGHT SIDEBAR -->
                        </div>
                    </div>
                </div>
                <!-- END CONTENT -->
            </div>
            <!-- END SIDEBAR & CONTENT -->


        </div>
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
    <div class="main">
        <div class="container">


            <div class="row margin-bottom-40">

                <div class="col-md-3 col-sm-3">

                    <!-- BEGIN RECENT NEWS -->
                    <h3><u>Recent Reviews</u></h3>
                    <div class="recent-news margin-bottom-10">


                        @foreach($recentPosts as $recentPost)
                            <div class="row margin-bottom-10">
                                <div class="col-md-3">
                                    <img class="img-responsive" alt="" src="{{config('Droids.admin').$recentPost->image}}">
                                </div>
                                <div class="col-md-9 recent-news-inner">
                                    <h3><a  href="{{$recentPost->url}}">{{$recentPost->title}}</a></h3>
                                    <p>
                                        {!! str_limit(strip_tags($recentPost->description), $limit = 100, $end = '...') !!}
                                    </p>
                                </div>
                            </div>
                        @endforeach
                    </div>
                    <!-- END RECENT NEWS -->

                </div>


                <div class="col-md-6 col-sm-6">
                    <!-- BEGIN CAROUSEL -->
                    <div class="front-carousel margin-bottom-20">
                        <div id="myCarousel" class="carousel slide">
                            <!-- Carousel items -->
                            <div class="carousel-inner">
                                <div class="item active">
                                    <img alt="{{$latest->title}}" src="{{config('Droids.admin').$latest->image}}" >
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- END CAROUSEL -->

                    <h2 class="no-top-space"><a href="{{$latest->url}}">{{$latest->title}}</a></h2>
                    <ul class="blog-info">
                        <li><i class="fa fa-user"></i> By {{\App\User::where('email', $latest->author)->first() ? \App\User::where('email', $latest->author)->first()->name : "N/A"}}</li>
                        <li><i class="fa fa-calendar"></i> {{$latest->created_at->toDayDateTimeString()}}</li>
                        <li><i class="fa fa-tags"></i> {{\App\SubCategory::find($latest->sub_category_id)->name}}</li>
                    </ul>
                    {{ str_limit(strip_tags($latest->description), $limit = 200, $end = '...') }}


                </div>


                <div class="col-md-3 col-sm-3">

                    <!-- BEGIN BLOG TAGS -->
                    <div class="blog-tags margin-bottom-20">
                        <h2>Tags</h2>
                        <ul>
                            @foreach(\App\SubCategory::all() as $subCat)
                                <li><a href="{{$subCat->url}}"><i class="fa fa-tags"></i>{{$subCat->name}}</a></li>
                            @endforeach
                        </ul>
                    </div>
                    <!-- END BLOG TAGS -->

                    <!-- BEGIN RECENT NEWS -->
                    {{--<h3><u>Deals we love <i class="fa fa-heart" style="color:#67bd3c"></i> </u></h3>--}}
                    {{--<div class="recent-news margin-bottom-10">--}}
                        {{--<div class="row margin-bottom-10">--}}
                            {{--<div class="col-md-3">--}}
                                {{--<img class="img-responsive" alt="" src="{{'img/personal-sound-amplification.jpg'}}">--}}
                            {{--</div>--}}
                            {{--<div class="col-md-9 recent-news-inner">--}}
                                {{--<h3><a href="#">The Best Personal Sound Amplification Product</a></h3>--}}
                                {{--<p>--}}
                                    {{--In 50 hours of research and testing, we’ve found that the Sound World Solutions CS50+...--}}
                                {{--</p>--}}
                            {{--</div>--}}
                        {{--</div>--}}

                        {{--<div class="row margin-bottom-10">--}}
                            {{--<div class="col-md-3">--}}
                                {{--<img class="img-responsive" alt="" src="{{'img/personal-sound-amplification.jpg'}}">--}}
                            {{--</div>--}}
                            {{--<div class="col-md-9 recent-news-inner">--}}
                                {{--<h3><a href="#">The Best Personal Sound Amplification Product</a></h3>--}}
                                {{--<p>--}}
                                    {{--In 50 hours of research and testing, we’ve found that the Sound World Solutions CS50+...--}}
                                {{--</p>--}}
                            {{--</div>--}}
                        {{--</div>--}}

                        {{--<div class="row margin-bottom-10">--}}
                            {{--<div class="col-md-3">--}}
                                {{--<img class="img-responsive" alt="" src="{{'img/personal-sound-amplification.jpg'}}">--}}
                            {{--</div>--}}
                            {{--<div class="col-md-9 recent-news-inner">--}}
                                {{--<h3><a href="#">The Best Personal Sound Amplification Product</a></h3>--}}
                                {{--<p>--}}
                                    {{--In 50 hours of research and testing, we’ve found that the Sound World Solutions CS50+...--}}
                                {{--</p>--}}
                            {{--</div>--}}
                        {{--</div>--}}
                    {{--</div>--}}
                    <!-- END RECENT NEWS -->

                </div>
            </div>


            <!-- BEGIN BLOCKQUOTE BLOCK -->
            <div class="row quote-v1 margin-bottom-30">
                <div class="col-md-12">
                    <span>The Dealersbay - We support our readers with hours of research to help you find the best gadgets/items to improve your life and make shopping easy. You support us through independently chosen links that earn us a commission</span>
                </div>
                {{--<div class="col-md-3 text-right">--}}
                    {{--<a class="btn-transparent" href="#"><i class="fa fa-rocket margin-right-10"></i>Get Started</a>--}}
                {{--</div>--}}
            </div>
            <!-- END BLOCKQUOTE BLOCK -->

            @foreach($categories as $category)
                @if(($category->id % 2) == 1)
                    <!-- BEGIN SERVICES -->
                        <div class="row front-team">
                            <h2 class="no-top-space text-left"><a href="{{$category->url}}">{{$category->name}} </a></h2>
                            <h4 class="no-top-space text-left">
                                @foreach(\App\SubCategory::where('category_id', $category->id)->get() as $subcategory)
                                    <a style="text-decoration: underline" href="{{$subcategory->url}}">{{$subcategory->name}}</a> ,
                                @endforeach
                            </h4>


                            <ul class="list-unstyled">

                                @foreach(\App\Post::whereIn('sub_category_id', \App\SubCategory::select('id')->where('category_id', $category->id)->get())->limit(3)->get() as $topPosts)
                                <li class="col-md-4">
                                        <img alt="{{$topPosts->title}}" src="{{config('Droids.admin').$topPosts->image}}" width="270" height="230"  >
                                        <h4>
                                            <a href="{{$topPosts->url}}"> <strong>{{$topPosts->title}}</strong> </a>
                                        </h4>

                                        <p>
                                            {{ str_limit(strip_tags($topPosts->description), $limit = 200, $end = '...') }}
                                        </p>
                                        <ul class="blog-info">
                                            <li><i class="fa fa-user"></i> By {{\App\User::where('email', $topPosts->author)->first()->name}}</li>
                                            <li><i class="fa fa-calendar"></i> {{$topPosts->created_at->toDayDateTimeString()}}</li>
                                            {{--<li><i class="fa fa-comments"></i> 17</li>--}}
                                            {{--<li><i class="fa fa-tags"></i> Tag1, tag2, tag3</li>--}}
                                        </ul>
                                </li>
                                @endforeach

                            </ul>
                        </div>
                        <!-- END SERVICES -->
                        <hr style="height:1px;border:none;color:#333;background-color:#333;">
                @else
                    <!-- BEGIN RECENT WORKS -->
                        <div class="row recent-work margin-bottom-40">
                            <div class="col-md-3">
                                <h2><a href="{{$category->url}}">{{$category->name}}</a></h2>
                                <p class="no-top-space text-left">
                                    @foreach(\App\SubCategory::where('category_id', $category->id)->get() as $subcategory)
                                        <a style="text-decoration: underline" href="{{$subcategory->url}}">{{$subcategory->name}}</a> ,
                                     @endforeach
                                <br>
                                <br>

                                {!! str_limit(strip_tags($category->description), $limit = 200, $end = '...') !!}


                            </div>
                            <div class="col-md-9">
                                <div class="owl-carousel owl-carousel3">


                                    @foreach(\App\Post::whereIn('sub_category_id', \App\SubCategory::select('id')->where('category_id', $category->id)->get())->limit(3)->get() as $topPosts)
                                        <div class="recent-work-item ">
                                            <em>
                                                <img alt="{{$topPosts->title}}" src="{{config('Droids.admin').$topPosts->image}}" width="270" height="230"  >

                                                <a href="{{$topPosts->url}}"><i class="fa fa-link"></i></a>
                                                <a href=" {{config('Droids.admin').$topPosts->image}}" class="fancybox-button" title="{{$topPosts->title}}" data-rel="fancybox-button"><i class="fa fa-search"></i></a>
                                            </em>
                                            <a class="recent-work-description" href="{{$topPosts->url}}">
                                                <strong>{{$topPosts->title}}</strong>

                                                {{ str_limit(strip_tags($topPosts->description), $limit = 100, $end = '...') }}
                                            </a>
                                        </div>
                                    @endforeach


                                </div>
                            </div>
                        </div>
                        <!-- END RECENT WORKS -->

                        <hr style="height:1px;border:none;color:#333;background-color:#333;">
                @endif

            @endforeach


            <!-- BEGIN STEPS -->
            <div class="row margin-bottom-40 front-steps-wrapper front-steps-count-3">
                <div class="col-md-4 col-sm-4 front-step-col">
                    <div class="front-step front-step1">
                        <h2>Review</h2>
                        <p>Gain insights of your favorite products before purchasing </p>
                    </div>
                </div>
                <div class="col-md-4 col-sm-4 front-step-col">
                    <div class="front-step front-step2">
                        <h2>Decide</h2>
                        <p>Use review knowledge to decide on what brand/type to buy.</p>
                    </div>
                </div>
                <div class="col-md-4 col-sm-4 front-step-col">
                    <div class="front-step front-step3">
                        <h2>Purchase</h2>
                        <p>
                            Purchase from a variety of different stores
                        </p>
                    </div>
                </div>
            </div>
            <!-- END STEPS -->


        </div>
    </div>
@endsection